### ISSUE TITLE
When I click on the cannon no confetti comes out?

### ISSUE THREAD

**Issue by boari1667** [tobysmith568/Confetti-Chrome-Extension#2]

**Comment by tobysmith568** [comment]
Hey - sorry for the late reply, I don't know how/why I didn't see this.

When you tried the button what page were you on? I ask because this, and all chrome extensions, cannot work on the extensions page/website of Chrome. You would need to navigate to a different website.

If you were elsewhere, and you're still looking to get this fixed, could you please reply with the error log for the extension assuming there is one? You can access it by going to your extensions page in your browser and clicking on "Errors" for this extension. Thanks
