### ISSUE TITLE
How to I make confetti fall during a Google Meet?

### ISSUE THREAD

**Issue by Katie711** [tobysmith568/Confetti-Chrome-Extension#3]

**Comment by tobysmith568** [comment]
Hey @Katie711 - could you be a little bit more specific with what you're after? For example, are you asking for confetti to appear over your webcam image? Because that would unfortunately be impossible.

If you're sharing your screen from within a Google Meet and you're sharing your web browser then the extension should already allow you to show that confetti over the call. Simply install it and press the button in the top right whenever you want confetti to fire.

**Comment by Katie711** [comment]
When I am just in a regular google meet, can I hit the button and make
confetti fall for everyone to see?

**Comment by hamen** [comment]
Yeah, I would love that as well, but I'm pretty sure it's impossible to achieve with a Google extension. This should come from the Google Meet team itself.
